import { PhysicsChemistryLessonReference } from "../../../types";

export const ac1InternationalLessons: PhysicsChemistryLessonReference[] = [
  {
    id: "pc-1ac-int-water",
    label: "L'eau",
    levelId: "1ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Connaître les sources naturelles de l'eau.",
      "Connaître l'importance de l'eau pour les êtres vivants.",
      "Connaître les trois états physiques de l'eau.",
      "Identifier les domaines d'utilisation de l'eau et proposer des mesures pratiques pour une utilisation rationnelle.",
    ],
    keywords: ["eau", "sources de l'eau", "états physiques", "utilisation de l'eau"],
  },
  {
    id: "pc-1ac-int-physical-transformations",
    label: "Les transformations physiques de la matière",
    levelId: "1ac",
    track: "international",
    defaultDurationHours: 4,
    defaultObjectives: [
      "Connaître les propriétés caractéristiques des états physiques de la matière.",
      "Distinguer les états physiques de la matière.",
      "Distinguer la température de la chaleur.",
      "Mesurer la température d'un corps à l'aide d'un thermomètre.",
      "Connaître l'unité Celsius de la température.",
      "Connaître le terme correspondant à chaque changement d'état physique (fusion, solidification, condensation, vaporisation).",
      "Connaître la conservation de la masse et la non-conservation du volume lors d'un changement d'état.",
      "Expliquer les changements d'état de la matière à partir du modèle particulaire.",
    ],
    keywords: ["transformations physiques", "états physiques", "température", "chaleur", "fusion", "vaporisation", "condensation", "solidification"],
  },
  {
    id: "pc-1ac-int-mixtures",
    label: "Les mélanges",
    levelId: "1ac",
    track: "international",
    defaultDurationHours: 4,
    defaultObjectives: [
      "Définir un mélange.",
      "Connaître les mélanges homogènes et hétérogènes.",
      "Classer les mélanges en homogènes et hétérogènes.",
      "Connaître la dissolution.",
      "Distinguer le solvant et le soluté dans une solution.",
      "Connaître quelques techniques de séparation des constituants d'un mélange : décantation, filtration, distillation.",
      "Distinguer un corps pur d'un mélange.",
      "Connaître les propriétés d'un corps pur.",
    ],
    keywords: ["mélanges", "mélange homogène", "mélange hétérogène", "dissolution", "solvant", "soluté", "filtration", "distillation"],
  },
  {
    id: "pc-1ac-int-water-treatment",
    label: "Le traitement des eaux",
    levelId: "1ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Connaître les sources de pollution de l'eau.",
      "Connaître les étapes du traitement des eaux usées.",
      "Proposer des mesures pratiques pour lutter contre la pollution de l'eau.",
    ],
    keywords: ["traitement des eaux", "pollution de l'eau", "purification", "eaux usées"],
  },
  {
    id: "pc-1ac-int-electricity-around-us",
    label: "L'électricité autour de nous",
    levelId: "1ac",
    track: "international",
    defaultDurationHours: 1,
    defaultObjectives: [
      "Connaître l'importance de l'électricité dans la vie quotidienne.",
    ],
    keywords: ["électricité", "vie quotidienne", "énergie électrique"],
  },
  {
    id: "pc-1ac-int-simple-electric-circuit",
    label: "Le circuit électrique simple",
    levelId: "1ac",
    track: "international",
    defaultDurationHours: 3,
    defaultObjectives: [
      "Connaître les éléments d'un circuit électrique simple.",
      "Représenter un circuit électrique à l'aide des symboles conventionnels.",
      "Réaliser un circuit électrique simple à partir d'un schéma et inversement.",
      "Définir un dipôle.",
      "Définir un conducteur et un isolant électrique.",
      "Distinguer les matériaux conducteurs des matériaux isolants.",
    ],
    keywords: ["circuit électrique", "éléments du circuit", "symboles électriques", "conducteur", "isolant", "dipôle"],
  },
  {
    id: "pc-1ac-int-electrical-connections",
    label: "Les montages électriques",
    levelId: "1ac",
    track: "international",
    defaultDurationHours: 3,
    defaultObjectives: [
      "Connaître les deux types de montage électrique.",
      "Réaliser un montage en série et un montage en dérivation de deux lampes à partir d'un schéma et inversement.",
      "Connaître l'intérêt du montage en dérivation.",
    ],
    keywords: ["montage électrique", "série", "dérivation", "lampe"],
  },
  {
    id: "pc-1ac-int-direct-current",
    label: "Le courant électrique continu",
    levelId: "1ac",
    track: "international",
    defaultDurationHours: 3,
    defaultObjectives: [
      "Connaître les sources du courant continu.",
      "Connaître les caractéristiques du courant continu.",
      "Utiliser des appareils de mesure pour mesurer l'intensité du courant et la tension.",
      "Connaître les unités de l'intensité du courant et de la tension dans le SI.",
    ],
    keywords: ["courant continu", "intensité", "tension", "appareils de mesure"],
  },
  {
    id: "pc-1ac-int-resistance-effect",
    label: "L'effet de la résistance électrique sur l'intensité du courant",
    levelId: "1ac",
    track: "international",
    defaultDurationHours: 3,
    defaultObjectives: [
      "Reconnaître le conducteur ohmique comme un dipôle caractérisé par une résistance électrique.",
      "Connaître le symbole et l'unité de la résistance électrique.",
      "Déterminer la valeur de la résistance à l'aide d'un ohmmètre.",
      "Connaître l'effet de la valeur de la résistance sur l'intensité du courant.",
      "Déterminer la valeur de la résistance à l'aide du code des couleurs.",
    ],
    keywords: ["résistance électrique", "conducteur ohmique", "ohmmètre", "intensité", "code des couleurs"],
  },
  {
    id: "pc-1ac-int-nodes-law",
    label: "La loi des nœuds – La loi d'additivité des tensions",
    levelId: "1ac",
    track: "international",
    defaultDurationHours: 4,
    defaultObjectives: [
      "Connaître la loi des nœuds et l'appliquer.",
      "Connaître la loi d'additivité des tensions et l'appliquer.",
    ],
    keywords: ["loi des nœuds", "additivité des tensions", "tension", "loi électrique"],
  },
  {
    id: "pc-1ac-int-electrical-safety",
    label: "La protection contre les dangers du courant électrique",
    levelId: "1ac",
    track: "international",
    defaultDurationHours: 3,
    defaultObjectives: [
      "Connaître la méthode de recherche des pannes électriques simples.",
      "Connaître le court-circuit et quelques-uns de ses dangers.",
      "Connaître le rôle protecteur du fusible.",
      "Connaître quelques dangers du courant électrique et les précautions à prendre.",
    ],
    keywords: ["sécurité électrique", "dangers électriques", "court-circuit", "fusible", "protection"],
  },
];
