import { PhysicsChemistryLessonReference } from "../../../types";

export const ac2InternationalLessons: PhysicsChemistryLessonReference[] = [
  {
    id: "pc-2ac-int-air-around-us",
    label: "L'air autour de nous",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Connaître les couches principales de l'atmosphère.",
      "Reconnaître le rôle protecteur de l'atmosphère, notamment la couche d'ozone.",
      "Reconnaître le mouvement de l'air dans l'atmosphère.",
      "Expliquer la formation des vents.",
    ],
    keywords: ["air", "atmosphère", "couches atmosphériques", "couche d'ozone", "vents"],
  },
  {
    id: "pc-2ac-int-air-properties-components",
    label: "Quelques propriétés de l'air et ses composants",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 1,
    defaultObjectives: [
      "Connaître que l'air pur est un mélange homogène.",
      "Connaître les principaux composants de l'air et leurs proportions.",
    ],
    keywords: ["propriétés de l'air", "composants de l'air", "mélange homogène", "diazote", "dioxygène"],
  },
  {
    id: "pc-2ac-int-molecules-atoms",
    label: "Les molécules et les atomes",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 3,
    defaultObjectives: [
      "Expliquer la compressibilité et la dilatation de l'air à partir du modèle moléculaire.",
      "Connaître la définition d'une molécule.",
      "Connaître la définition d'un atome.",
      "Connaître l'ordre de grandeur du diamètre d'un atome.",
      "Connaître les symboles chimiques : C, H, O, N et leurs noms.",
      "Écrire les formules chimiques : H₂, O₂, N₂, H₂O, CO₂, C₄H₁₀, CO à partir du nom ou inversement.",
      "Définir un corps simple et un corps composé et les distinguer.",
    ],
    keywords: ["molécules", "atomes", "modèle moléculaire", "symboles chimiques", "formules chimiques", "corps simple", "corps composé"],
  },
  {
    id: "pc-2ac-int-combustion",
    label: "Les combustions",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 4,
    defaultObjectives: [
      "Reconnaître que la combustion est une transformation chimique.",
      "Connaître les produits de combustion du carbone et du butane dans le dioxygène.",
      "Connaître le réactif de détection du dioxyde de carbone.",
      "Distinguer la combustion complète de la combustion incomplète.",
      "Reconnaître les dangers de la combustion incomplète.",
      "Reconnaître quelques produits de combustion des cigarettes et leurs conséquences sur la santé.",
    ],
    keywords: ["combustions", "transformation chimique", "combustion complète", "combustion incomplète", "dioxygène", "CO₂", "carbone", "butane"],
  },
  {
    id: "pc-2ac-int-chemical-reaction-concept",
    label: "La notion de réaction chimique",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 1,
    defaultObjectives: [
      "Connaître la notion de réaction chimique.",
      "Distinguer la transformation physique de la transformation chimique.",
      "Écrire l'équation de réaction en utilisant les noms des réactifs et des produits.",
    ],
    keywords: ["réaction chimique", "transformation physique", "transformation chimique", "réactifs", "produits"],
  },
  {
    id: "pc-2ac-int-chemical-reaction-laws",
    label: "Les lois de la réaction chimique",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 5,
    defaultObjectives: [
      "Connaître la loi de conservation de la masse et la loi de conservation des atomes lors d'une transformation chimique.",
      "Appliquer les lois de la réaction chimique.",
      "Écrire l'équation chimique à partir des formules chimiques des réactifs et des produits.",
      "Équilibrer une équation chimique en appliquant la loi de conservation des atomes.",
    ],
    keywords: ["lois de la réaction chimique", "conservation de la masse", "conservation des atomes", "équation chimique", "équilibrage"],
  },
  {
    id: "pc-2ac-int-natural-industrial-materials",
    label: "Les matières naturelles et les matières industrielles",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Distinguer les matières naturelles des matières industrielles.",
      "Connaître que les composants du pétrole sont des matières naturelles.",
      "Reconnaître la méthode de séparation des composants du pétrole.",
      "Connaître quelques dérivés naturels et industriels du pétrole et leurs domaines d'utilisation.",
      "Reconnaître quelques matières industrielles polluantes pour l'eau et l'air.",
    ],
    keywords: ["matières naturelles", "matières industrielles", "pétrole", "dérivés du pétrole", "pollution"],
  },
  {
    id: "pc-2ac-int-air-pollution",
    label: "La pollution de l'air",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Reconnaître quelques causes de la pollution de l'air.",
      "Connaître l'effet de la pollution sur la santé et l'environnement.",
      "Reconnaître des mesures et comportements quotidiens pour limiter la pollution de l'air.",
      "Être conscient des dangers de la pollution de l'air.",
    ],
    keywords: ["pollution de l'air", "causes de pollution", "santé", "environnement"],
  },
  {
    id: "pc-2ac-int-light-around-us",
    label: "La lumière autour de nous",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 1,
    defaultObjectives: [
      "Connaître l'importance de la lumière dans la vie quotidienne.",
    ],
    keywords: ["lumière", "vie quotidienne"],
  },
  {
    id: "pc-2ac-int-light-sources-receptors",
    label: "Les sources et les récepteurs de lumière",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Connaître quelques sources lumineuses.",
      "Distinguer les sources lumineuses primaires des sources lumineuses secondaires.",
      "Connaître quelques récepteurs de lumière.",
    ],
    keywords: ["sources de lumière", "récepteurs de lumière", "sources primaires", "sources secondaires"],
  },
  {
    id: "pc-2ac-int-light-colors-dispersion",
    label: "La lumière et les couleurs – La dispersion de la lumière",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Connaître le phénomène de dispersion de la lumière blanche et sa recomposition.",
      "Connaître que la lumière monochromatique ne se disperse pas.",
    ],
    keywords: ["lumière", "couleurs", "dispersion", "lumière blanche", "lumière monochromatique"],
  },
  {
    id: "pc-2ac-int-light-propagation",
    label: "La propagation de la lumière",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 3,
    defaultObjectives: [
      "Classer les différents milieux de propagation de la lumière.",
      "Reconnaître les phénomènes liés à la propagation : diffusion, réflexion, absorption.",
      "Connaître et appliquer le principe de propagation rectiligne dans un milieu transparent et homogène.",
      "Connaître le sens de propagation et la vitesse de la lumière dans le vide.",
      "Distinguer les différents faisceaux lumineux.",
      "Utiliser le modèle du rayon lumineux pour représenter les faisceaux.",
    ],
    keywords: ["propagation de la lumière", "milieux de propagation", "diffusion", "réflexion", "propagation rectiligne", "vitesse de la lumière", "rayon lumineux"],
  },
  {
    id: "pc-2ac-int-rectilinear-propagation-applications",
    label: "Applications de la propagation rectiligne de la lumière",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Connaître le principe de la chambre noire.",
      "Construire l'image obtenue par une chambre noire.",
      "Connaître les types d'ombres et les expliquer.",
      "Expliquer les phénomènes d'éclipse solaire et lunaire.",
    ],
    keywords: ["chambre noire", "ombres", "rayon lumineux", "éclipse"],
  },
  {
    id: "pc-2ac-int-thin-lenses",
    label: "Les lentilles minces",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 4,
    defaultObjectives: [
      "Reconnaître une lentille mince convergente et divergente.",
      "Connaître les caractéristiques d'une lentille convergente.",
      "Déterminer expérimentalement la distance focale d'une lentille convergente.",
      "Connaître et exploiter l'expression de la vergence d'une lentille.",
      "Connaître les conditions de Gauss et les rayons particuliers.",
      "Réaliser la construction géométrique de l'image d'un objet lumineux.",
      "Déterminer graphiquement les caractéristiques de l'image (position, taille, nature).",
    ],
    keywords: ["lentilles minces", "lentille convergente", "distance focale", "vergence", "conditions de Gauss", "rayons particuliers", "image réelle", "image virtuelle"],
  },
  {
    id: "pc-2ac-int-optical-instruments",
    label: "Applications : étude de quelques instruments d'optique",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Connaître le principe de la loupe et construire graphiquement son image.",
      "Connaître le modèle réduit de l'œil.",
      "Reconnaître les défauts de la vision : myopie, hypermétropie et leur correction.",
    ],
    keywords: ["instruments d'optique", "loupe", "œil", "myopie", "hypermétropie"],
  },
  {
    id: "pc-2ac-int-alternating-current",
    label: "Le courant électrique alternatif sinusoïdal",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Connaître la fonction de l'oscilloscope.",
      "Distinguer une tension continue d'une tension alternative sinusoïdale.",
      "Connaître les caractéristiques : période, fréquence, valeur maximale, valeur efficace.",
      "Utiliser un oscillogramme pour déterminer quelques caractéristiques.",
      "Connaître et appliquer la relation entre valeur maximale et valeur efficace.",
    ],
    keywords: ["courant alternatif sinusoïdal", "tension sinusoïdale", "oscilloscope", "période", "fréquence", "valeur maximale", "valeur efficace"],
  },
  {
    id: "pc-2ac-int-home-electrical-installation",
    label: "L'installation électrique domestique",
    levelId: "2ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Reconnaître les fils de l'installation monophasée.",
      "Connaître le type de l'installation électrique domestique et ses éléments principaux.",
      "Connaître quelques dangers du courant électrique domestique et les précautions à prendre.",
      "Connaître l'ordre de grandeur de la tension dangereuse pour le corps humain.",
    ],
    keywords: ["installation électrique domestique", "monophasée", "fils électriques", "dangers électriques", "protection"],
  },
];
