import { PhysicsChemistryLessonReference } from "../../../types";

export const ac3InternationalLessons: PhysicsChemistryLessonReference[] = [
  {
    id: "pc-3ac-int-materials-daily-life",
    label: "Exemples de matériaux utilisés dans notre vie quotidienne",
    levelId: "3ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Distinguer les objets des matières qui les constituent.",
      "Classer les matières métalliques, verreuses et plastiques selon leurs propriétés.",
      "Connaître les propriétés de quelques matières : fer, cuivre, polyéthylène (P.E).",
      "Être conscient de l'importance du choix des matériaux d'emballage appropriés.",
    ],
    keywords: ["matériaux", "propriétés", "classification", "métaux", "verre", "plastique", "fer", "cuivre", "P.E", "emballage"],
  },
  {
    id: "pc-3ac-int-atom-electricity",
    label: "Les matières et l'électricité",
    levelId: "3ac",
    track: "international",
    defaultDurationHours: 4,
    defaultObjectives: [
      "Connaître les constituants de l'atome (noyau et électrons).",
      "Connaître la signification du numéro atomique Z.",
      "Connaître la neutralité électrique de l'atome.",
      "Connaître l'ion et le classer en ion monoatomique et ion polyatomique.",
      "Écrire la formule d'un ion en connaissant le nombre d'électrons gagnés ou perdus.",
    ],
    keywords: ["matières", "électricité", "atome", "noyau", "électrons", "numéro atomique", "Z", "ion", "charge", "neutralité électrique"],
  },
  {
    id: "pc-3ac-int-oxidation-air",
    label: "Réactions de quelques matières avec l'air",
    levelId: "3ac",
    track: "international",
    defaultDurationHours: 4,
    defaultObjectives: [
      "Connaître les facteurs favorisant l'oxydation du fer dans l'air humide.",
      "Connaître quelques propriétés de la rouille et comment la limiter.",
      "Expliquer la différence entre l'oxydation de l'aluminium et celle du fer dans l'air.",
      "Connaître le nom et la formule de Al₂O₃ et Fe₂O₃.",
      "Écrire l'équation de la réaction correspondant à la formation de Al₂O₃ et Fe₂O₃.",
      "Reconnaître les produits de combustion de quelques matières organiques dans le dioxygène.",
      "Identifier les atomes entrant dans la composition d'une matière organique à partir des produits de sa combustion.",
      "Connaître les dangers de la combustion des matières organiques sur la santé et l'environnement.",
    ],
    keywords: ["réactions", "matières", "air", "oxydation", "combustion", "rouille", "Fe₂O₃", "Al₂O₃", "dioxygène"],
  },
  {
    id: "pc-3ac-int-reactions-solutions",
    label: "Réactions de quelques matières avec des solutions",
    levelId: "3ac",
    track: "international",
    defaultDurationHours: 8,
    defaultObjectives: [
      "Connaître la signification du pH.",
      "Utiliser le pH-mètre et le papier pH pour mesurer le pH d'une solution aqueuse.",
      "Classer les solutions aqueuses en acides, basiques et neutres selon les valeurs de pH.",
      "Connaître quelques dangers des solutions acides et basiques et appliquer les précautions nécessaires.",
      "Reconnaître la dilution d'une solution acide et basique et son effet sur le pH.",
      "Reconnaître l'action de l'acide chlorhydrique sur le fer, le cuivre, le zinc et l'aluminium.",
      "Reconnaître l'action de l'hydroxyde de sodium sur le fer, le cuivre, le zinc et l'aluminium.",
      "Connaître les réactifs de détection des ions : Cl⁻, Fe³⁺, Fe²⁺, Al³⁺, Zn²⁺, Cu²⁺.",
    ],
    keywords: ["réactions", "solutions", "pH", "acide", "base", "solution aqueuse", "Cl⁻", "Fe³⁺", "Zn²⁺", "Cu²⁺"],
  },
  {
    id: "pc-3ac-int-environment-risk",
    label: "Dangers de quelques matières utilisées dans la vie quotidienne",
    levelId: "3ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Connaître les dangers des déchets de matières non biodégradables dans la nature.",
      "Connaître quelques méthodes de gestion des déchets et de recyclage.",
      "Être conscient de l'importance de la préservation de la santé et de l'environnement.",
    ],
    keywords: ["dangers", "matières", "santé", "environnement", "déchets", "recyclage", "pollution"],
  },
  {
    id: "pc-3ac-int-motion-rest",
    label: "Le mouvement et le repos",
    levelId: "3ac",
    track: "international",
    defaultDurationHours: 5,
    defaultObjectives: [
      "Connaître le référentiel.",
      "Connaître l'état de mouvement et de repos d'un solide par rapport à un référentiel.",
      "Connaître la trajectoire.",
      "Connaître les deux types de mouvement d'un solide (translation, rotation) et les distinguer.",
      "Connaître l'expression de la vitesse moyenne et son unité en SI (m.s⁻¹) et calculer sa valeur en m.s⁻¹ et km.h⁻¹.",
      "Connaître et déterminer la nature du mouvement en translation (uniforme, accéléré, décéléré).",
      "Connaître quelques facteurs influençant la distance d'arrêt lors d'un freinage.",
      "Connaître les dangers de l'excès de vitesse et en être conscient.",
      "Connaître quelques règles de sécurité routière et les appliquer.",
    ],
    keywords: ["mouvement", "repos", "vitesse", "m.s⁻¹", "km.h⁻¹", "trajectoire", "référentiel", "translation", "rotation"],
  },
  {
    id: "pc-3ac-int-mechanical-forces",
    label: "Les effets mécaniques – Les forces",
    levelId: "3ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Connaître les effets mécaniques et identifier leurs effets.",
      "Connaître les deux catégories d'effets mécaniques.",
      "Distinguer l'action de contact de l'action à distance.",
      "Connaître qu'un effet mécanique est associé à une force.",
    ],
    keywords: ["effets mécaniques", "forces", "force", "action de contact", "action à distance"],
  },
  {
    id: "pc-3ac-int-force-concept",
    label: "La notion de force",
    levelId: "3ac",
    track: "international",
    defaultDurationHours: 3,
    defaultObjectives: [
      "Connaître et déterminer les caractéristiques d'une force.",
      "Mesurer l'intensité d'une force à l'aide d'un dynamomètre.",
      "Représenter une force par un vecteur à l'aide d'une échelle appropriée.",
    ],
    keywords: ["notion de force", "force", "dynamomètre", "vecteur", "intensité", "représentation"],
  },
  {
    id: "pc-3ac-int-equilibrium-forces",
    label: "Équilibre d'un solide soumis à deux forces",
    levelId: "3ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Connaître et appliquer la condition d'équilibre.",
    ],
    keywords: ["équilibre", "solide", "deux forces", "condition d'équilibre", "force"],
  },
  {
    id: "pc-3ac-int-weight-mass",
    label: "Le poids et la masse",
    levelId: "3ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Connaître et déterminer les caractéristiques du poids d'un solide.",
      "Distinguer le poids de la masse.",
      "Connaître et exploiter la relation P = m.g.",
    ],
    keywords: ["poids", "masse", "P = m.g", "gravité", "pesanteur"],
  },
  {
    id: "pc-3ac-int-ohm-law",
    label: "La résistance électrique – La loi d'Ohm",
    levelId: "3ac",
    track: "international",
    defaultDurationHours: 1,
    defaultObjectives: [
      "Réaliser un montage expérimental simplifié pour vérifier la loi d'Ohm.",
      "Connaître la loi d'Ohm et l'appliquer.",
    ],
    keywords: ["résistance", "électrique", "loi d'Ohm", "U", "I", "R", "circuit électrique"],
  },
  {
    id: "pc-3ac-int-electric-power",
    label: "La puissance électrique",
    levelId: "3ac",
    track: "international",
    defaultDurationHours: 2,
    defaultObjectives: [
      "Connaître la puissance électrique et son unité (le watt).",
      "Connaître quelques ordres de grandeur de la puissance électrique.",
      "Connaître les caractéristiques nominales d'un appareil électrique.",
      "Déterminer la puissance électrique consommée par un appareil de chauffage.",
      "Connaître et exploiter la relation P = U.I.",
    ],
    keywords: ["puissance", "électrique", "watt", "P = U.I", "tension", "intensité", "appareil électrique"],
  },
  {
    id: "pc-3ac-int-electric-energy",
    label: "L'énergie électrique",
    levelId: "3ac",
    track: "international",
    defaultDurationHours: 3,
    defaultObjectives: [
      "Connaître que l'énergie électrique consommée par un appareil de chauffage se convertit en énergie thermique.",
      "Connaître l'énergie électrique et ses unités (joule, watt-heure).",
      "Connaître et exploiter la relation E = P.t.",
      "Déterminer l'énergie électrique consommée par un appareil de chauffage.",
      "Connaître le rôle du compteur électrique dans une installation domestique.",
      "Déterminer l'énergie électrique consommée dans une installation domestique à partir de la facture ou du compteur.",
    ],
    keywords: ["énergie", "électrique", "E = P.t", "joule", "watt-heure", "compteur électrique", "énergie thermique"],
  },
];
